[package]
name = "libbuf"
version = "0.2.4"
edition = "2021"
publish = false
description = "Core logic library for the buf USB flasher tool"

[dependencies]
anyhow    = "1"
log       = "0.4"
fern      = "0.6"
chrono    = { version = "0.4", features = ["clock"] }
indicatif = "0.17"
fatfs     = "0.3"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["user", "process"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Devices_DeviceAndDriverInstallation",
] }
